'use strict'

const { contextBridge, ipcRenderer } = require('electron')

const CHANNELS = Object.freeze({
  bootstrap: 'fanotes:bootstrap',
  rendererReady: 'fanotes:renderer-ready',
  completeOnboarding: 'fanotes:complete-onboarding',
  getCachedTree: 'fanotes:get-cached-tree',
  getFastTree: 'fanotes:get-fast-tree',
  selectVault: 'fanotes:select-vault',
  getTree: 'fanotes:get-tree',
  readFile: 'fanotes:read-file',
  writeFile: 'fanotes:write-file',
  createNote: 'fanotes:create-note',
  createFolder: 'fanotes:create-folder',
  setFolderColor: 'fanotes:set-folder-color',
  renameEntry: 'fanotes:rename-entry',
  moveEntry: 'fanotes:move-entry',
  trashEntry: 'fanotes:trash-entry',
  search: 'fanotes:search',
  saveDrawing: 'fanotes:save-drawing',
  listDrawings: 'fanotes:list-drawings',
  readDrawing: 'fanotes:read-drawing',
  readFamdInk: 'fanotes:read-famd-ink',
  readNotePaperStyle: 'fanotes:read-note-paper-style',
  setNotePaperStyle: 'fanotes:set-note-paper-style',
  importWorksheet: 'fanotes:import-worksheet',
  importWorksheetFromData: 'fanotes:import-worksheet-from-data',
  importPdfNote: 'fanotes:import-pdf-note',
  importOneNote: 'fanotes:import-onenote',
  readWorksheet: 'fanotes:read-worksheet',
  saveWorksheet: 'fanotes:save-worksheet',
  deleteWorksheet: 'fanotes:delete-worksheet',
  listNoteHistory: 'fanotes:list-note-history',
  readNoteHistory: 'fanotes:read-note-history',
  exportNotePdf: 'fanotes:export-note-pdf',
  readAssetDataUrl: 'fanotes:read-asset-data-url',
  readAssetBytes: 'fanotes:read-asset-bytes',
  loadSpellingResources: 'fanotes:load-spelling-resources',
  loadSpellingWordCandidates: 'fanotes:load-spelling-word-candidates',
  loadHandwritingRecognitionResources: 'fanotes:load-handwriting-recognition-resources',
  recognizeNativeHandwritingLine: 'fanotes:recognize-native-handwriting-line',
  enhancedMathGetState: 'fanotes:enhanced-math-get-state',
  enhancedMathInstall: 'fanotes:enhanced-math-install',
  enhancedMathRecognize: 'fanotes:enhanced-math-recognize',
  qwenVisionGetState: 'fanotes:qwen-vision-get-state',
  qwenVisionInstall: 'fanotes:qwen-vision-install',
  qwenVisionRecognize: 'fanotes:qwen-vision-recognize',
  lmStudioListModels: 'fanotes:lm-studio-list-models',
  lmStudioTransform: 'fanotes:lm-studio-transform',
  aiListModels: 'fanotes:ai-list-models',
  aiTransform: 'fanotes:ai-transform',
  loadSecureSettings: 'fanotes:load-secure-settings',
  saveSettings: 'fanotes:save-settings',
  resetAppData: 'fanotes:reset-app-data',
  updateGetState: 'fanotes:update-get-state',
  updateCheck: 'fanotes:update-check',
  updateDownload: 'fanotes:update-download',
  updateInstall: 'fanotes:update-install',
  updateState: 'fanotes:update-state',
  revealInFolder: 'fanotes:reveal-in-folder',
  openExternal: 'fanotes:open-external',
  beforeClose: 'fanotes:before-close',
  confirmClose: 'fanotes:confirm-close',
  cancelClose: 'fanotes:cancel-close',
  requestClose: 'fanotes:request-close',
  sheetZoom: 'fanotes:sheet-zoom',
  captureWindow: 'fanotes:capture-window',
})

const invoke = (channel, ...args) => ipcRenderer.invoke(channel, ...args)

const api = Object.freeze({
  bootstrap: () => invoke(CHANNELS.bootstrap),
  reportRendererReady: () => ipcRenderer.send(CHANNELS.rendererReady),
  completeOnboarding: (subjects) => invoke(CHANNELS.completeOnboarding, subjects),
  selectVault: () => invoke(CHANNELS.selectVault),
  getCachedTree: () => invoke(CHANNELS.getCachedTree),
  getFastTree: () => invoke(CHANNELS.getFastTree),
  getTree: () => invoke(CHANNELS.getTree),
  readFile: (relativePath) => invoke(CHANNELS.readFile, relativePath),
  writeFile: (relativePath, content) => invoke(CHANNELS.writeFile, relativePath, content),
  createNote: (parentPath, preferredName) => invoke(CHANNELS.createNote, parentPath, preferredName),
  createFolder: (parentPath, preferredName) => invoke(CHANNELS.createFolder, parentPath, preferredName),
  setFolderColor: (relativePath, color) => invoke(CHANNELS.setFolderColor, relativePath, color),
  renameEntry: (relativePath, nextName) => invoke(CHANNELS.renameEntry, relativePath, nextName),
  moveEntry: (relativePath, destFolder) => invoke(CHANNELS.moveEntry, relativePath, destFolder),
  trashEntry: (relativePath) => invoke(CHANNELS.trashEntry, relativePath),
  search: (query) => invoke(CHANNELS.search, query),
  saveDrawing: (payload) => invoke(CHANNELS.saveDrawing, payload),
  listDrawings: () => invoke(CHANNELS.listDrawings),
  readDrawing: (id) => invoke(CHANNELS.readDrawing, id),
  readFamdInk: (relativePath) => invoke(CHANNELS.readFamdInk, relativePath),
  readNotePaperStyle: (relativePath) => invoke(CHANNELS.readNotePaperStyle, relativePath),
  setNotePaperStyle: (relativePath, paperStyle) => invoke(CHANNELS.setNotePaperStyle, relativePath, paperStyle),
  importWorksheet: () => invoke(CHANNELS.importWorksheet),
  importWorksheetFromData: (payload) => invoke(CHANNELS.importWorksheetFromData, payload),
  importPdfNote: (parentPath) => invoke(CHANNELS.importPdfNote, parentPath),
  importOneNote: () => invoke(CHANNELS.importOneNote),
  readWorksheet: (id) => invoke(CHANNELS.readWorksheet, id),
  saveWorksheet: (document) => invoke(CHANNELS.saveWorksheet, document),
  deleteWorksheet: (id) => invoke(CHANNELS.deleteWorksheet, id),
  listNoteHistory: (relativePath) => invoke(CHANNELS.listNoteHistory, relativePath),
  readNoteHistory: (relativePath, snapshotId) => invoke(CHANNELS.readNoteHistory, relativePath, snapshotId),
  exportNotePdf: () => invoke(CHANNELS.exportNotePdf),
  readAssetDataUrl: (relativePath) => invoke(CHANNELS.readAssetDataUrl, relativePath),
  readAssetBytes: (relativePath) => invoke(CHANNELS.readAssetBytes, relativePath),
  loadSpellingResources: () => invoke(CHANNELS.loadSpellingResources),
  loadSpellingWordCandidates: (language) => invoke(CHANNELS.loadSpellingWordCandidates, language),
  loadHandwritingRecognitionResources: () => invoke(CHANNELS.loadHandwritingRecognitionResources),
  recognizeNativeHandwritingLine: (request) => invoke(CHANNELS.recognizeNativeHandwritingLine, request),
  getEnhancedMathRecognitionState: () => invoke(CHANNELS.enhancedMathGetState),
  installEnhancedMathRecognitionModel: (request) => invoke(CHANNELS.enhancedMathInstall, request),
  recognizeEnhancedMath: (request) => invoke(CHANNELS.enhancedMathRecognize, request),
  getQwenVisionState: () => invoke(CHANNELS.qwenVisionGetState),
  installQwenVisionModel: (request) => invoke(CHANNELS.qwenVisionInstall, request),
  recognizeQwenVision: (request) => invoke(CHANNELS.qwenVisionRecognize, request),
  lmStudioListModels: (baseUrl, apiToken) => invoke(CHANNELS.lmStudioListModels, baseUrl, apiToken),
  lmStudioTransform: (payload) => invoke(CHANNELS.lmStudioTransform, payload),
  aiListModels: (connection) => invoke(CHANNELS.aiListModels, connection),
  aiTransform: (payload) => invoke(CHANNELS.aiTransform, payload),
  loadSecureSettings: () => invoke(CHANNELS.loadSecureSettings),
  saveSettings: (settings, options) => invoke(CHANNELS.saveSettings, settings, options),
  resetAppData: () => invoke(CHANNELS.resetAppData),
  getUpdateState: () => invoke(CHANNELS.updateGetState),
  checkForUpdates: () => invoke(CHANNELS.updateCheck),
  downloadUpdate: () => invoke(CHANNELS.updateDownload),
  installUpdate: () => invoke(CHANNELS.updateInstall),
  onUpdateState: (callback) => {
    if (typeof callback !== 'function') return () => {}
    const listener = (_event, state) => callback(state)
    ipcRenderer.on(CHANNELS.updateState, listener)
    return () => ipcRenderer.removeListener(CHANNELS.updateState, listener)
  },
  revealInFolder: (relativePath) => invoke(CHANNELS.revealInFolder, relativePath),
  openExternal: (url) => invoke(CHANNELS.openExternal, url),
  onBeforeClose: (callback) => {
    if (typeof callback !== 'function') return () => {}
    const listener = () => callback()
    ipcRenderer.on(CHANNELS.beforeClose, listener)
    return () => ipcRenderer.removeListener(CHANNELS.beforeClose, listener)
  },
  confirmClose: () => ipcRenderer.send(CHANNELS.confirmClose),
  cancelClose: () => ipcRenderer.send(CHANNELS.cancelClose),
  requestClose: () => ipcRenderer.send(CHANNELS.requestClose),
  onSheetZoom: (callback) => {
    if (typeof callback !== 'function') return () => {}
    const listener = (_event, direction) => callback(direction)
    ipcRenderer.on(CHANNELS.sheetZoom, listener)
    return () => ipcRenderer.removeListener(CHANNELS.sheetZoom, listener)
  },
  captureWindow: () => invoke(CHANNELS.captureWindow),
  platform: process.platform,
})

contextBridge.exposeInMainWorld('fanotes', api)
