import type { AppSettings } from './types'

export const DEFAULT_SETTINGS: AppSettings = {
  uiLanguage: 'system',
  theme: 'dark',
  workspaceBackground: 'gradient',
  accent: '#8b7cff',
  accentSecondary: '#45c9b7',
  uiFont: "'DM Sans', ui-sans-serif, system-ui",
  editorFont: "'JetBrains Mono', ui-monospace, monospace",
  editorFontSize: 16,
  previewFontSize: 17,
  lineHeight: 1.72,
  readableLineLength: true,
  contentWidth: 820,
  showLineNumbers: false,
  spellcheck: true,
  vimMode: false,
  autosaveDelay: 750,
  sidebarWidth: 286,
  rightPanelWidth: 286,
  compactMode: false,
  glassEffects: true,
  reduceMotion: false,
  showWordCount: true,
  showOutline: true,
  defaultFolder: 'Eingang',
  dailyNotesFolder: 'Tagesnotizen',
  dateFormat: 'YYYY-MM-DD',
  paperStyle: 'dots',
  penColor: '#202333',
  penWidth: 3.5,
  pressureEnabled: true,
  smoothing: 0.68,
  scribbleEraseSensitivity: 50,
  recognitionMode: 'auto',
  lastRecognitionMode: 'text',
  recognitionLanguage: 'de',
  autoOpenConversion: false,
  keepDrawingAfterInsert: true,
  autoCheckUpdates: true,
  autoDownloadUpdates: true,
  installUpdatesOnQuit: true,
  updateChannel: 'stable',
  memoryBudgetMb: 0,
  ocrThreadLimit: 0,
  desktopOcrModel: 'extended',
  ocrModelKeepAliveSeconds: 120,
  backgroundTaskLimit: 0,
  lmStudioBaseUrl: 'http://127.0.0.1:1234',
  lmStudioModel: '',
  lmStudioApiToken: '',
  aiProvider: 'lmstudio',
  ollamaBaseUrl: 'http://127.0.0.1:11434',
  ollamaModel: '',
  ollamaApiToken: '',
  openAiModel: '',
  openAiApiKey: '',
  geminiModel: '',
  geminiApiKey: '',
  anthropicModel: '',
  anthropicApiKey: '',
  openCodeBaseUrl: 'http://127.0.0.1:4096',
  openCodeModel: '',
  openCodeUsername: 'opencode',
  openCodePassword: '',
  customCss: '',
}
